# Generated by Django 2.1.2 on 2018-11-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descriptions', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='committee_photo')),
                ('leaderNumber', models.IntegerField()),
                ('memberNumber', models.IntegerField()),
                ('created_On', models.DateTimeField(auto_now_add=True)),
                ('updated_On', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_On'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.Committee')),
            ],
        ),
    ]
