# Generated by Django 2.1.2 on 2018-11-25 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0006_auto_20181125_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideview',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideview',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slideview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='committee_photo', verbose_name='Select Image'),
        ),
    ]
