# Generated by Django 2.1.2 on 2018-11-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0007_auto_20181125_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideview',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='committee.Committee'),
        ),
    ]
